---
# Install and enable ntp service

- name: Make sure ntp is installed
  package: name=ntp state=installed
  tags: ntp

- name: Make sure ntp is configured
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntpd
  tags: ntp

- name: Make sure ntpd is running and enabled
  service: name=ntp state=running enabled=yes
  tags: ntp
